---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  tasks:
  - name: make data directory
    file:
      path: /data
      state: directory
  - name: format volume
    command: mkfs.ext4 /dev/xvdf
  - name: mount formatted volume on /data
    mount:
      path: /data
      src: /dev/xvdf
      fstype: ext4
      state: present
  - name: install docker
    yum:
      name: docker
      state: latest
  - name: install git
    yum:
      name: git
      state: latest
  - name: ensure docker is running
    service:
      name: docker
      state: started
  - name: enable docker deamon
    service:
      name: docker
      enabled: yes
  - name: pull jenkins image
    command: docker pull jenkins/jenkins
  - name: run jenkins container
    command: docker run -dit --name jenkins -u root -p 8080:8080 -v /data/:/var/jenkins_home jenkins/jenkins
  - name: make workspace directory for jenkins job
    file:
      path: /data/workspace/website
      state: directory
  - name: pull httpd image
    command: docker pull httpd
  - name: run httpd container
    command: docker run -dit --name webserver -p 80:80 -v /data/workspace/website/:/usr/local/apache2/htdocs/ httpd 
  - name: cat initial jenkin password
    shell: cat initialAdminPassword
    args:
      chdir: /data/secrets/

